language: php

php:
- 7.0
- 7.1
- hhvm
- hhvm-nightly

# service yang digunakan
services:
  - docker
# grouping  task
jobs:
  include:
  # melakukan testing 
    - stage: "Tests"                
      name: "Unit Test PHP"  
      before_script:
      - composer self-update
      - composer install --prefer-source --no-interaction --dev
      - cp .env.example .env
      - php artisan key:generate
      script:
      - tests/Feature/ExampleTest.php
    # melakukan build images dan publish ke docker hub
    - stage: "Build Docker Image"
      name: "Build Images Docker" 
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t travis-ci-build-stages-demo .
      - docker images
      - docker tag travis-ci-build-stages-demo $DOCKER_USERNAME/cicd_pelatihan
      - docker push $DOCKER_USERNAME/cicd_pelatihan
